version: '3.1'

services:
  mongo:
    build: mongo
    ports:
      - "27017:27017"
    command: ["--replSet", "rs"]
    hostname: "mongo"

  perflab_httpd:
    build:
      context: ..
      dockerfile: Dockerfile.devel
    ports:
      - "8000:8000"
    command: ["./perflab-httpd.js"]
    depends_on:
      mongo:
        condition: service_healthy
    links:
      - mongo
